export const vaccins = [
  {
    nom: 'BBIBP-CorV',
    inventeurs: 'Sinopharm',
    lieuxDeProduction: 'Chine',
    technologie: 'virus inactivé',
    quantite: 420,
    prixUnitaire: '17$',
    approuve: true,
    image: 'bbibp-corv.jpg',
  },
  {
    nom: 'Sputnik V',
    inventeurs: 'Gamaleya',
    lieuxDeProduction: ['Russie, Inde'],
    technologie: 'adenovirus',
    quantite: 130,
    prixUnitaire: '12$',
    approuve: false,
    image: 'sputnik-v.jpg',
  },
  {
    nom: 'AZD1222',
    inventeurs: ['AstraZeneca, University of Oxford '],
    lieuxDeProduction: ['Royaume Unis, Brésil, Inde'],
    technologie: 'adenovirus',
    quantite: 5028,
    prixUnitaire: '1.78$',
    approuve: false,
    image: 'azd1222.jpg',
  },
  {
    nom: 'Tozinameran',
    inventeurs: ['BioNTech, Pfizer, Fosun Pharma'],
    lieuxDeProduction: ['Allemagne, USA'],
    technologie: 'ARN messager',
    quantite: 980,
    prixUnitaire: '14$',
    approuve: true,
    image: 'tozinameran.jpg',
  },
  {
    nom: 'mRNA-1273',
    inventeurs: ['Moderna, NIAID, BARDA'],
    lieuxDeProduction: 'USA',
    technologie: 'ARN messager',
    quantite: 240,
    prixUnitaire: '28$',
    approuve: false,
    image: 'mrna-1273.jpg',
  },
  {
    nom: 'Ad26.COV2.S',
    inventeurs: ['Johnson & Johnson, BIDMC'],
    lieuxDeProduction: ['USA, Amérique du Sud, Ukraine, Afrique du Sud'],
    technologie: 'adenovirus ',
    quantite: 110,
    prixUnitaire: '31$',
    approuve: false,
    image: 'ad26-cov2-s.jpg',
  },
];
